# Generated by Django 3.2.7 on 2022-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_year',
            field=models.CharField(max_length=250),
        ),
    ]
