# Generated by Django 3.2.7 on 2022-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_auto_20220414_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
