# Generated by Django 3.2.7 on 2022-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
