# Generated by Django 3.2.7 on 2022-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0009_auto_20220414_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
