# Generated by Django 4.0.4 on 2022-04-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0012_auto_20220415_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('College', 'College'), ('High School', 'High School'), ('Elementary', 'Elementary'), ('Kindergarten', 'Kindergarten'), ('Day Care', 'Day Care'), ('Out of School', 'Out of School'), ('Graduates', 'Graduates')], max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_year',
            field=models.CharField(blank=True, choices=[('K1', 'K1'), ('K2', 'K2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=250, null=True),
        ),
    ]
